In [1]:
import numpy as np
import pandas as pd

In [330]:
col=pd.read_csv('C://Users//287910031/9781839213106_Code//data/college.csv',index_col='INSTNM')

In [331]:
columns=col.columns

In [5]:
columns

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL',
       'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE',
       'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI',
       'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'PCTPELL',
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP'],
      dtype='object')

In [6]:
columns.values

array(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY',
       'RELAFFIL', 'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS',
       'UGDS_WHITE', 'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN',
       'UGDS_NHPI', 'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF',
       'CURROPER', 'PCTPELL', 'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10',
       'GRAD_DEBT_MDN_SUPP'], dtype=object)

In [7]:
columns[5]

'WOMENONLY'

In [9]:
columns[[4,2,9]]

Index(['MENONLY', 'STABBR', 'DISTANCEONLY'], dtype='object')

In [10]:
columns[-7:-4]

Index(['PPTUG_EF', 'CURROPER', 'PCTPELL'], dtype='object')

In [14]:
columns.min(),columns.max(),columns.isnull().sum()

('CITY', 'WOMENONLY', 0)

In [15]:
columns+"_A"

Index(['INSTNM_A', 'CITY_A', 'STABBR_A', 'HBCU_A', 'MENONLY_A', 'WOMENONLY_A',
       'RELAFFIL_A', 'SATVRMID_A', 'SATMTMID_A', 'DISTANCEONLY_A', 'UGDS_A',
       'UGDS_WHITE_A', 'UGDS_BLACK_A', 'UGDS_HISP_A', 'UGDS_ASIAN_A',
       'UGDS_AIAN_A', 'UGDS_NHPI_A', 'UGDS_2MOR_A', 'UGDS_NRA_A',
       'UGDS_UNKN_A', 'PPTUG_EF_A', 'CURROPER_A', 'PCTPELL_A', 'PCTFLOAN_A',
       'UG25ABV_A', 'MD_EARN_WNE_P10_A', 'GRAD_DEBT_MDN_SUPP_A'],
      dtype='object')

In [16]:
columns

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU', 'MENONLY', 'WOMENONLY', 'RELAFFIL',
       'SATVRMID', 'SATMTMID', 'DISTANCEONLY', 'UGDS', 'UGDS_WHITE',
       'UGDS_BLACK', 'UGDS_HISP', 'UGDS_ASIAN', 'UGDS_AIAN', 'UGDS_NHPI',
       'UGDS_2MOR', 'UGDS_NRA', 'UGDS_UNKN', 'PPTUG_EF', 'CURROPER', 'PCTPELL',
       'PCTFLOAN', 'UG25ABV', 'MD_EARN_WNE_P10', 'GRAD_DEBT_MDN_SUPP'],
      dtype='object')

In [17]:
c1=columns[:4]

In [18]:
c1

Index(['INSTNM', 'CITY', 'STABBR', 'HBCU'], dtype='object')

In [21]:
c2=columns[2:6]

c2

Index(['STABBR', 'HBCU', 'MENONLY', 'WOMENONLY'], dtype='object')

In [20]:
c1|c2

Index(['CITY', 'HBCU', 'INSTNM', 'MENONLY', 'STABBR', 'WOMENONLY'], dtype='object')

In [22]:
c1.union(c2)

Index(['CITY', 'HBCU', 'INSTNM', 'MENONLY', 'STABBR', 'WOMENONLY'], dtype='object')

In [23]:
c1^c2

Index(['CITY', 'INSTNM', 'MENONLY', 'WOMENONLY'], dtype='object')

In [24]:
c1.symmetric_difference(c2)

Index(['CITY', 'INSTNM', 'MENONLY', 'WOMENONLY'], dtype='object')

In [26]:
s1=pd.Series(index=list("aaab"),data=np.arange(4))

In [27]:
s1

a    0
a    1
a    2
b    3
dtype: int32

In [30]:
s2=pd.Series(index=list("cababb"),data=np.arange(6))

s2

c    0
a    1
b    2
a    3
b    4
b    5
dtype: int32

In [29]:
s1+s2

a    1.0
a    3.0
a    2.0
a    4.0
a    3.0
a    5.0
b    5.0
b    7.0
b    8.0
c    NaN
dtype: float64

In [31]:
s1 = pd.Series(index=list("aaabb"), data=np.arange(5))
s2 = pd.Series(index=list("aaabb"), data=np.arange(5))

s1+s2

a    0
a    2
a    4
b    6
b    8
dtype: int32

In [32]:
s1 = pd.Series(index=list("aaabb"), data=np.arange(5))
s2 = pd.Series(index=list("bbaaa"), data=np.arange(5))

s1+s2

a    2
a    3
a    4
a    3
a    4
a    5
a    4
a    5
a    6
b    3
b    4
b    4
b    5
dtype: int32

In [33]:
emp=pd.read_csv('C://Users//287910031/9781839213106_Code//data/employee.csv',index_col="RACE")

In [34]:
emp.head()

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
RACE,,,,,,,,,
Hispanic/Latino,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Full Time,Female,Active,2006-06-12,2012-10-13
Hispanic/Latino,1,LIBRARY ASSISTANT,Library,26125.0,Full Time,Female,Active,2000-07-19,2010-09-18
White,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,Full Time,Male,Active,2015-02-03,2015-02-03
White,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,Full Time,Male,Active,1982-02-08,1991-05-25
White,4,ELECTRICIAN,General Services Department,56347.0,Full Time,Male,Active,1989-06-19,1994-10-22

In [36]:
s1=emp['BASE_SALARY']
s2=emp['BASE_SALARY']

In [39]:
s1 is s2

True

In [40]:
s2=emp['BASE_SALARY'].copy()

In [42]:
s1 is s2

False

In [44]:
s1=s1.sort_index()

In [45]:
s2.head()

RACE
Hispanic/Latino    121862.0
Hispanic/Latino     26125.0
White               45279.0
White               63166.0
White               56347.0
Name: BASE_SALARY, dtype: float64

In [47]:
sadd=s1+s2

In [48]:
sadd.head()

RACE
American Indian or Alaskan Native    138702.0
American Indian or Alaskan Native    156710.0
American Indian or Alaskan Native    176891.0
American Indian or Alaskan Native    159594.0
American Indian or Alaskan Native    127734.0
Name: BASE_SALARY, dtype: float64

In [49]:
sadd1=s1+s1

In [53]:
( len(s1),len(s2),len(sadd),len(sadd1) )

(2000, 2000, 1175424, 2000)

In [55]:
baseball_14=pd.read_csv('C://Users//287910031/9781839213106_Code//data//baseball14.csv',index_col='playerID')
baseball_15=pd.read_csv('C://Users//287910031/9781839213106_Code//data//baseball15.csv',index_col='playerID')
baseball_16=pd.read_csv('C://Users//287910031/9781839213106_Code//data//baseball16.csv',index_col='playerID')

In [56]:
baseball_14.head()

,yearID,stint,teamID,lgID,G,AB,R,H,2B,3B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
playerID,,,,,,,,,,,,,,,,,,,,,
altuvjo01,2014,1,HOU,AL,158,660,85,225,47,3,...,59.0,56.0,9.0,36,53.0,7.0,5.0,1.0,5.0,20.0
cartech02,2014,1,HOU,AL,145,507,68,115,21,1,...,88.0,5.0,2.0,56,182.0,6.0,5.0,0.0,4.0,12.0
castrja01,2014,1,HOU,AL,126,465,43,103,21,2,...,56.0,1.0,0.0,34,151.0,1.0,9.0,1.0,3.0,11.0
corpoca01,2014,1,HOU,AL,55,170,22,40,6,0,...,19.0,0.0,0.0,14,37.0,0.0,3.0,1.0,2.0,3.0
dominma01,2014,1,HOU,AL,157,564,51,121,17,0,...,57.0,0.0,1.0,29,125.0,2.0,5.0,2.0,7.0,23.0

In [57]:
baseball_14.index.difference(baseball_15.index)

Index(['corpoca01', 'dominma01', 'fowlede01', 'grossro01', 'guzmaje01',
       'hoeslj01', 'krausma01', 'preslal01', 'singljo02'],
      dtype='object', name='playerID')

In [58]:
baseball_15.index.difference(baseball_14.index)

Index(['congeha01', 'correca01', 'gattiev01', 'gomezca01', 'lowrije01',
       'rasmuco01', 'tuckepr01', 'valbulu01'],
      dtype='object', name='playerID')

In [60]:
hits_14=baseball_14['H']
hits_15=baseball_15['H']
hits_16=baseball_16['H']

In [62]:
(hits_14+hits_15).head()

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01      NaN
corpoca01      NaN
Name: H, dtype: float64

In [64]:
hits_14.add(hits_15,fill_value=0)

playerID
altuvjo01    425.0
cartech02    193.0
castrja01    174.0
congeha01     46.0
corpoca01     40.0
correca01    108.0
dominma01    121.0
fowlede01    120.0
gattiev01    139.0
gomezca01     36.0
gonzama01    175.0
grossro01     84.0
guzmaje01     31.0
hoeslj01      21.0
krausma01     36.0
lowrije01     51.0
marisja01    127.0
preslal01     62.0
rasmuco01    103.0
singljo02     52.0
springe01    175.0
tuckepr01     73.0
valbulu01     97.0
villajo01     88.0
Name: H, dtype: float64

In [65]:
hits_total=hits_14.add(hits_15,fill_value=0).add(hits_16,fill_value=0)

In [66]:
hits_total.isna().sum()

0

In [68]:
hits_total.hasnans

False

In [69]:
s = pd.Series(index=["a", "b", "c", "d"],data=[np.nan, 3, np.nan, 1])

In [70]:
s1 = pd.Series(index=["a", "b", "c"], data=[np.nan, 6, 10])

In [71]:
s

a    NaN
b    3.0
c    NaN
d    1.0
dtype: float64

In [72]:
s1

a     NaN
b     6.0
c    10.0
dtype: float64

In [74]:
s.add(s1,fill_value=5)

a     NaN
b     9.0
c    15.0
d     6.0
dtype: float64

In [77]:
df_14=baseball_14[['G','AB','R','H']]

df_15=baseball_15[["AB", "R", "H", "HR"]]

In [78]:
df_14.head()

             G   AB   R    H
playerID
altuvjo01  158  660  85  225
cartech02  145  507  68  115
castrja01  126  465  43  103
corpoca01   55  170  22   40
dominma01  157  564  51  121

In [79]:
df_15.head()

            AB   R    H  HR
playerID
altuvjo01  638  86  200  15
cartech02  391  50   78  24
castrja01  337  38   71  11
congeha01  201  25   46  11
correca01  387  52  108  22

In [82]:
df_14.add(df_15).head().style.highlight_null('yellow')

In [83]:
df_14.add(df_15,fill_value=0).head().style.highlight_null('yellow')

In [143]:
emp=pd.read_csv('C://Users//287910031/9781839213106_Code//data/employee.csv')

In [144]:
dept_sal=emp[['DEPARTMENT','BASE_SALARY']]

In [145]:
dept_sal.head()

                      DEPARTMENT  BASE_SALARY
0    Municipal Courts Department     121862.0
1                        Library      26125.0
2  Houston Police Department-HPD      45279.0
3  Houston Fire Department (HFD)      63166.0
4    General Services Department      56347.0

In [146]:
dept_sal=dept_sal.sort_values(['DEPARTMENT','BASE_SALARY'],ascending=[True,False])

In [147]:
dept_sal.head()

                      DEPARTMENT  BASE_SALARY
1494  Admn. & Regulatory Affairs     140416.0
237   Admn. & Regulatory Affairs     130416.0
1679  Admn. & Regulatory Affairs     103776.0
988   Admn. & Regulatory Affairs      72741.0
693   Admn. & Regulatory Affairs      66825.0

In [148]:
max_dep_sal=dept_sal.drop_duplicates(subset='DEPARTMENT')

In [149]:
max_dep_sal.head()

                        DEPARTMENT  BASE_SALARY
1494    Admn. & Regulatory Affairs     140416.0
149       City Controller's Office      64251.0
236                   City Council     100000.0
647   Convention and Entertainment      38397.0
1500   Dept of Neighborhoods (DON)      89221.0

In [150]:
max_dep_sal=max_dep_sal.set_index('DEPARTMENT')
max_dep_sal.head()

                              BASE_SALARY
DEPARTMENT
Admn. & Regulatory Affairs       140416.0
City Controller's Office          64251.0
City Council                     100000.0
Convention and Entertainment      38397.0
Dept of Neighborhoods (DON)       89221.0

In [151]:
emp.columns

Index(['UNIQUE_ID', 'POSITION_TITLE', 'DEPARTMENT', 'BASE_SALARY', 'RACE',
       'EMPLOYMENT_TYPE', 'GENDER', 'EMPLOYMENT_STATUS', 'HIRE_DATE',
       'JOB_DATE'],
      dtype='object')

In [152]:
employee=emp.set_index('DEPARTMENT')
employee.head()

,UNIQUE_ID,POSITION_TITLE,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
DEPARTMENT,,,,,,,,,
Municipal Courts Department,0,ASSISTANT DIRECTOR (EX LVL),121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13
Library,1,LIBRARY ASSISTANT,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18
Houston Police Department-HPD,2,POLICE OFFICER,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03
Houston Fire Department (HFD),3,ENGINEER/OPERATOR,63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25
General Services Department,4,ELECTRICIAN,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22

In [153]:
employee=employee.assign(MAX_DEP_SAL=max_dep_sal['BASE_SALARY'])

In [154]:
employee

,UNIQUE_ID,POSITION_TITLE,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE,MAX_DEP_SAL
DEPARTMENT,,,,,,,,,,
Municipal Courts Department,0,ASSISTANT DIRECTOR (EX LVL),121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13,121862.0
Library,1,LIBRARY ASSISTANT,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18,107763.0
Houston Police Department-HPD,2,POLICE OFFICER,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03,199596.0
Houston Fire Department (HFD),3,ENGINEER/OPERATOR,63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25,210588.0
General Services Department,4,ELECTRICIAN,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22,89194.0
Houston Police Department-HPD,5,SENIOR POLICE OFFICER,66614.0,Black or African American,Full Time,Male,Active,1984-11-26,2005-03-26,199596.0
Public Works & Engineering-PWE,6,ENGINEER,71680.0,Asian/Pacific Islander,Full Time,Male,Active,2012-03-26,2012-03-26,178331.0
Houston Airport System (HAS),7,CARPENTER,42390.0,White,Full Time,Male,Active,2013-11-04,2013-11-04,186192.0
Public Works & Engineering-PWE,8,DEPUTY ASSISTANT DIRECTOR (EXECUTIVE LEV,107962.0,White,Full Time,Male,Active,1993-11-15,2013-01-05,178331.0
Houston Airport System (HAS),9,AIRPORT OPERATIONS COORDINATOR,44616.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14,186192.0
Houston Fire Department (HFD),10,FIRE FIGHTER,52644.0,Hispanic/Latino,Full Time,Male,Active,2007-05-21,2008-11-15,210588.0
Health & Human Services,11,"CHIEF PHYSICIAN,MD",180416.0,Black or African American,Full Time,Male,Active,1987-05-22,1999-08-28,180416.0
Public Works & Engineering-PWE,12,CUSTOMER SERVICE REPRESENTATIVE I,30347.0,Black or African American,Full Time,Male,Active,2015-11-16,2015-11-16,178331.0
Health & Human Services,13,PUBLIC HEALTH INVESTIGATOR SUPERVISOR,55269.0,Black or African American,Full Time,Male,Active,1999-10-20,2001-05-19,180416.0
Houston Police Department-HPD,14,POLICE SERGEANT,77076.0,Black or African American,Full Time,Male,Active,2001-06-04,2015-05-25,199596.0
Houston Police Department-HPD,15,SENIOR POLICE OFFICER,NaN,Black or African American,Full Time,Male,Active,1995-01-30,2015-02-14,199596.0
Houston Police Department-HPD,16,SENIOR POLICE OFFICER,NaN,Hispanic/Latino,Full Time,Male,Active,1981-02-23,2002-01-05,199596.0
Houston Police Department-HPD,17,POLICE SERGEANT,81239.0,White,Full Time,Male,Active,1995-06-19,2007-03-03,199596.0
General Services Department,18,MAINTENANCE MECHANIC III,40581.0,Hispanic/Latino,Full Time,Male,Active,2008-12-29,2008-12-29,89194.0
Houston Police Department-HPD,19,SENIOR POLICE OFFICER,66614.0,White,Full Time,Male,Active,1992-02-17,2007-07-28,199596.0
Public Works & Engineering-PWE,20,SENIOR INSPECTOR,61506.0,White,Full Time,Male,Active,2009-04-06,2015-04-11,178331.0
Houston Fire Department (HFD),21,FIRE FIGHTER,57815.0,Black or African American,Full Time,Male,Active,2001-03-20,2003-01-04,210588.0
Public Works & Engineering-PWE,22,INSPECTOR,43264.0,Black or African American,Full Time,Male,Active,2015-01-05,2015-01-05,178331.0
Houston Fire Department (HFD),23,FIRE FIGHTER,55437.0,White,Full Time,Male,Active,2004-03-15,2005-03-26,210588.0
Houston Police Department-HPD,24,POLICE OFFICER,52514.0,Black or African American,Full Time,Male,Active,2010-03-29,2011-03-29,199596.0
Houston Police Department-HPD,25,SENIOR POLICE OFFICER,61643.0,White,Full Time,Male,Active,1999-08-23,2012-03-31,199596.0
Houston Police Department-HPD,26,SENIOR POLICE OFFICER,NaN,Hispanic/Latino,Full Time,Male,Active,1979-11-19,2015-12-19,199596.0
Houston Police Department-HPD,27,SENIOR POLICE OFFICER,66614.0,White,Full Time,Male,Active,1990-01-12,2004-07-03,199596.0
Houston Police Department-HPD,28,POLICE SERGEANT,81239.0,White,Full Time,Male,Active,1978-03-13,1994-09-10,199596.0
Public Works & Engineering-PWE,29,UTILITY WORKER,29557.0,Black or African American,Full Time,Male,Active,2014-01-21,2014-01-21,178331.0
...,...,...,...,...,...,...,...,...,...,...
Houston Police Department-HPD,1970,SENIOR POLICE OFFICER,66614.0,Hispanic/Latino,Full Time,Male,Active,1990-06-11,2002-12-07,199596.0
Houston Police Department-HPD,1971,POLICE OFFICER,45279.0,Hispanic/Latino,Full Time,Female,Active,2013-10-14,2014-10-14,199596.0
Houston Fire Department (HFD),1972,ENGINEER/OPERATOR,63166.0,White,Full Time,Male,Active,1990-12-10,2001-04-28,210588.0
Public Works & Engineering-PWE,1973,SENIOR PROJECT MANAGER,77325.0,White,Full Time,Male,Active,2008-08-04,2012-07-07,178331.0
Houston Police Department-HPD,1974,SENIOR POLICE OFFICER,66614.0,Black or African American,Full Time,Male,Active,1993-04-12,2013-10-12,199596.0
Houston Airport System (HAS),1975,GROUND TRANSPORTATION REPRESENTATIVE,32157.0,Asian/Pacific Islander,Full Time,Female,Active,1993-05-13,2000-07-15,186192.0
Solid Waste Management,1976,SENIOR SIDELOADER OPERATOR,34466.0,Hispanic/Latino,Full Time,Female,Active,2015-07-20,2016-01-30,110005.0
Houston Police Department-HPD,1977,POLICE OFFICER,45279.0,White,Full Time,Male,Active,2013-06-10,2014-06-10,199596.0
Houston Police Department-HPD,1978,POLICE SERVICE OFFICER,27914.0,Black or African American,Full Time,Female,Active,2011-10-14,2014-03-01,199596.0
Houston Police Department-HPD,1979,SENIOR POLICE OFFICER,66614.0,Hispanic/Latino,Full Time,Male,Active,1993-11-08,2006-06-03,199596.0
Houston Police Department-HPD,1980,SENIOR POLICE OFFICER,NaN,White,Full Time,Male,Active,1983-10-03,2006-05-06,199596.0
Houston Fire Department (HFD),1981,CAPTAIN,70181.0,Black or African American,Full Time,Male,Active,1994-08-29,2013-09-04,210588.0
Houston Fire Department (HFD),1982,FIRE FIGHTER,55437.0,Black or African American,Full Time,Male,Active,2004-01-05,2005-01-14,210588.0
Admn. & Regulatory Affairs,1983,ADMINISTRATIVE SPECIALIST,55172.0,Black or African American,Full Time,Female,Active,2006-10-16,2006-10-16,140416.0
Houston Fire Department (HFD),1984,ENGINEER/OPERATOR,61921.0,White,Full Time,Male,Active,2006-09-11,2014-06-11,210588.0
Fleet Management Department,1985,TRUCK DRIVER,30222.0,Black or African American,Full Time,Male,Active,2013-06-10,2015-08-01,125884.0
Houston Police Department-HPD,1986,POLICE SERGEANT,77076.0,White,Full Time,Male,Active,2001-12-03,2010-12-10,199596.0
Houston Police Department-HPD,1987,SENIOR POLICE OFFICER,NaN,White,Full Time,Male,Active,1977-05-23,2002-01-05,199596.0
Legal Department,1988,SENIOR ASSISTANT CITY ATTORNEY II,124115.0,White,Full Time,Male,Active,2013-01-23,2013-03-02,275000.0
Public Works & Engineering-PWE,1989,EQUIPMENT WORKER,37211.0,Black or African American,Full Time,Male,Active,1984-12-11,2004-09-18,178331.0
Parks & Recreation,1990,BUILDING MAINTENANCE SUPERVISOR,30347.0,Black or African American,Full Time,Female,Active,1995-10-14,2010-03-20,85055.0
Houston Police Department-HPD,1991,MOBILITY SERVICE OFFICER,44429.0,Hispanic/Latino,Full Time,Female,Active,2005-09-12,2007-06-02,199596.0
Houston Airport System (HAS),1992,SECURITY OFFICER,29286.0,Hispanic/Latino,Full Time,Male,Active,2011-12-12,2011-12-12,186192.0
Houston Police Department-HPD,1993,POLICE SERGEANT,81239.0,White,Full Time,Male,Active,1982-05-03,2011-09-03,199596.0
Houston Police Department-HPD,1994,POLICE CAPTAIN,104455.0,Black or African American,Full Time,Male,Active,1983-02-07,2004-07-08,199596.0
Houston Police Department-HPD,1995,POLICE OFFICER,43443.0,White,Full Time,Male,Active,2014-06-09,2015-06-09,199596.0
Houston Fire Department (HFD),1996,COMMUNICATIONS CAPTAIN,66523.0,Black or African American,Full Time,Male,Active,2003-09-02,2013-10-06,210588.0
Houston Police Department-HPD,1997,POLICE OFFICER,43443.0,White,Full Time,Male,Active,2014-10-13,2015-10-13,199596.0
Houston Police Department-HPD,1998,POLICE OFFICER,55461.0,Asian/Pacific Islander,Full Time,Male,Active,2009-01-20,2011-07-02,199596.0
Houston Fire Department (HFD),1999,FIRE FIGHTER,51194.0,Hispanic/Latino,Full Time,Male,Active,2009-01-12,2010-07-12,210588.0

In [156]:
employee[employee['BASE_SALARY'] > employee['MAX_DEP_SAL']]

Empty DataFrame
Columns: [UNIQUE_ID, POSITION_TITLE, BASE_SALARY, RACE, EMPLOYMENT_TYPE, GENDER, EMPLOYMENT_STATUS, HIRE_DATE, JOB_DATE, MAX_DEP_SAL]
Index: []

In [158]:
employee.query('BASE_SALARY>MAX_DEP_SAL')

Empty DataFrame
Columns: [UNIQUE_ID, POSITION_TITLE, BASE_SALARY, RACE, EMPLOYMENT_TYPE, GENDER, EMPLOYMENT_STATUS, HIRE_DATE, JOB_DATE, MAX_DEP_SAL]
Index: []

In [165]:
random_o=dept_sal.sample(n=10,random_state=42).set_index('DEPARTMENT')

In [166]:
random_o

                                BASE_SALARY
DEPARTMENT
Public Works & Engineering-PWE      34861.0
Houston Airport System (HAS)        29286.0
Houston Police Department-HPD       31907.0
Houston Police Department-HPD       66614.0
Houston Police Department-HPD       42000.0
Houston Police Department-HPD       43443.0
Houston Police Department-HPD       66614.0
Public Works & Engineering-PWE      52582.0
Finance                             93168.0
Houston Police Department-HPD       35318.0

In [167]:
employee['RANDOM_SALARY']=random_o['BASE_SALARY']

ValueError: cannot reindex from a duplicate axis

In [172]:
(employee.assign(RANDMAXSAL2=max_dep_sal['BASE_SALARY'].head(3)) ).RANDMAXSAL2.value_counts()

140416.0    29
100000.0    11
64251.0      5
Name: RANDMAXSAL2, dtype: int64

In [181]:
employee=pd.read_csv('C://Users//287910031/9781839213106_Code//data/employee.csv')

In [179]:
max_sal=(employee.groupby('DEPARTMENT')['BASE_SALARY'].transform('max') )

In [180]:
employee.assign(MAX_DEPT_SALARY=max_sal)

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE,MAX_DEPT_SALARY
0,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13,121862.0
1,1,LIBRARY ASSISTANT,Library,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18,107763.0
2,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03,199596.0
3,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25,210588.0
4,4,ELECTRICIAN,General Services Department,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22,89194.0
5,5,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Black or African American,Full Time,Male,Active,1984-11-26,2005-03-26,199596.0
6,6,ENGINEER,Public Works & Engineering-PWE,71680.0,Asian/Pacific Islander,Full Time,Male,Active,2012-03-26,2012-03-26,178331.0
7,7,CARPENTER,Houston Airport System (HAS),42390.0,White,Full Time,Male,Active,2013-11-04,2013-11-04,186192.0
8,8,DEPUTY ASSISTANT DIRECTOR (EXECUTIVE LEV,Public Works & Engineering-PWE,107962.0,White,Full Time,Male,Active,1993-11-15,2013-01-05,178331.0
9,9,AIRPORT OPERATIONS COORDINATOR,Houston Airport System (HAS),44616.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14,186192.0
10,10,FIRE FIGHTER,Houston Fire Department (HFD),52644.0,Hispanic/Latino,Full Time,Male,Active,2007-05-21,2008-11-15,210588.0
11,11,"CHIEF PHYSICIAN,MD",Health & Human Services,180416.0,Black or African American,Full Time,Male,Active,1987-05-22,1999-08-28,180416.0
12,12,CUSTOMER SERVICE REPRESENTATIVE I,Public Works & Engineering-PWE,30347.0,Black or African American,Full Time,Male,Active,2015-11-16,2015-11-16,178331.0
13,13,PUBLIC HEALTH INVESTIGATOR SUPERVISOR,Health & Human Services,55269.0,Black or African American,Full Time,Male,Active,1999-10-20,2001-05-19,180416.0
14,14,POLICE SERGEANT,Houston Police Department-HPD,77076.0,Black or African American,Full Time,Male,Active,2001-06-04,2015-05-25,199596.0
15,15,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Black or African American,Full Time,Male,Active,1995-01-30,2015-02-14,199596.0
16,16,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Hispanic/Latino,Full Time,Male,Active,1981-02-23,2002-01-05,199596.0
17,17,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1995-06-19,2007-03-03,199596.0
18,18,MAINTENANCE MECHANIC III,General Services Department,40581.0,Hispanic/Latino,Full Time,Male,Active,2008-12-29,2008-12-29,89194.0
19,19,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,White,Full Time,Male,Active,1992-02-17,2007-07-28,199596.0
20,20,SENIOR INSPECTOR,Public Works & Engineering-PWE,61506.0,White,Full Time,Male,Active,2009-04-06,2015-04-11,178331.0
21,21,FIRE FIGHTER,Houston Fire Department (HFD),57815.0,Black or African American,Full Time,Male,Active,2001-03-20,2003-01-04,210588.0
22,22,INSPECTOR,Public Works & Engineering-PWE,43264.0,Black or African American,Full Time,Male,Active,2015-01-05,2015-01-05,178331.0
23,23,FIRE FIGHTER,Houston Fire Department (HFD),55437.0,White,Full Time,Male,Active,2004-03-15,2005-03-26,210588.0
24,24,POLICE OFFICER,Houston Police Department-HPD,52514.0,Black or African American,Full Time,Male,Active,2010-03-29,2011-03-29,199596.0
25,25,SENIOR POLICE OFFICER,Houston Police Department-HPD,61643.0,White,Full Time,Male,Active,1999-08-23,2012-03-31,199596.0
26,26,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Hispanic/Latino,Full Time,Male,Active,1979-11-19,2015-12-19,199596.0
27,27,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,White,Full Time,Male,Active,1990-01-12,2004-07-03,199596.0
28,28,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1978-03-13,1994-09-10,199596.0
29,29,UTILITY WORKER,Public Works & Engineering-PWE,29557.0,Black or African American,Full Time,Male,Active,2014-01-21,2014-01-21,178331.0
...,...,...,...,...,...,...,...,...,...,...,...
1970,1970,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Hispanic/Latino,Full Time,Male,Active,1990-06-11,2002-12-07,199596.0
1971,1971,POLICE OFFICER,Houston Police Department-HPD,45279.0,Hispanic/Latino,Full Time,Female,Active,2013-10-14,2014-10-14,199596.0
1972,1972,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1990-12-10,2001-04-28,210588.0
1973,1973,SENIOR PROJECT MANAGER,Public Works & Engineering-PWE,77325.0,White,Full Time,Male,Active,2008-08-04,2012-07-07,178331.0
1974,1974,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Black or African American,Full Time,Male,Active,1993-04-12,2013-10-12,199596.0
1975,1975,GROUND TRANSPORTATION REPRESENTATIVE,Houston Airport System (HAS),32157.0,Asian/Pacific Islander,Full Time,Female,Active,1993-05-13,2000-07-15,186192.0
1976,1976,SENIOR SIDELOADER OPERATOR,Solid Waste Management,34466.0,Hispanic/Latino,Full Time,Female,Active,2015-07-20,2016-01-30,110005.0
1977,1977,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2013-06-10,2014-06-10,199596.0
1978,1978,POLICE SERVICE OFFICER,Houston Police Department-HPD,27914.0,Black or African American,Full Time,Female,Active,2011-10-14,2014-03-01,199596.0
1979,1979,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Hispanic/Latino,Full Time,Male,Active,1993-11-08,2006-06-03,199596.0
1980,1980,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,White,Full Time,Male,Active,1983-10-03,2006-05-06,199596.0
1981,1981,CAPTAIN,Houston Fire Department (HFD),70181.0,Black or African American,Full Time,Male,Active,1994-08-29,2013-09-04,210588.0
1982,1982,FIRE FIGHTER,Houston Fire Department (HFD),55437.0,Black or African American,Full Time,Male,Active,2004-01-05,2005-01-14,210588.0
1983,1983,ADMINISTRATIVE SPECIALIST,Admn. & Regulatory Affairs,55172.0,Black or African American,Full Time,Female,Active,2006-10-16,2006-10-16,140416.0
1984,1984,ENGINEER/OPERATOR,Houston Fire Department (HFD),61921.0,White,Full Time,Male,Active,2006-09-11,2014-06-11,210588.0
1985,1985,TRUCK DRIVER,Fleet Management Department,30222.0,Black or African American,Full Time,Male,Active,2013-06-10,2015-08-01,125884.0
1986,1986,POLICE SERGEANT,Houston Police Department-HPD,77076.0,White,Full Time,Male,Active,2001-12-03,2010-12-10,199596.0
1987,1987,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,White,Full Time,Male,Active,1977-05-23,2002-01-05,199596.0
1988,1988,SENIOR ASSISTANT CITY ATTORNEY II,Legal Department,124115.0,White,Full Time,Male,Active,2013-01-23,2013-03-02,275000.0
1989,1989,EQUIPMENT WORKER,Public Works & Engineering-PWE,37211.0,Black or African American,Full Time,Male,Active,1984-12-11,2004-09-18,178331.0
1990,1990,BUILDING MAINTENANCE SUPERVISOR,Parks & Recreation,30347.0,Black or African American,Full Time,Female,Active,1995-10-14,2010-03-20,85055.0
1991,1991,MOBILITY SERVICE OFFICER,Houston Police Department-HPD,44429.0,Hispanic/Latino,Full Time,Female,Active,2005-09-12,2007-06-02,199596.0
1992,1992,SECURITY OFFICER,Houston Airport System (HAS),29286.0,Hispanic/Latino,Full Time,Male,Active,2011-12-12,2011-12-12,186192.0
1993,1993,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1982-05-03,2011-09-03,199596.0
1994,1994,POLICE CAPTAIN,Houston Police Department-HPD,104455.0,Black or African American,Full Time,Male,Active,1983-02-07,2004-07-08,199596.0
1995,1995,POLICE OFFICER,Houston Police Department-HPD,43443.0,White,Full Time,Male,Active,2014-06-09,2015-06-09,199596.0
1996,1996,COMMUNICATIONS CAPTAIN,Houston Fire Department (HFD),66523.0,Black or African American,Full Time,Male,Active,2003-09-02,2013-10-06,210588.0
1997,1997,POLICE OFFICER,Houston Police Department-HPD,43443.0,White,Full Time,Male,Active,2014-10-13,2015-10-13,199596.0
1998,1998,POLICE OFFICER,Houston Police Department-HPD,55461.0,Asian/Pacific Islander,Full Time,Male,Active,2009-01-20,2011-07-02,199596.0
1999,1999,FIRE FIGHTER,Houston Fire Department (HFD),51194.0,Hispanic/Latino,Full Time,Male,Active,2009-01-12,2010-07-12,210588.0

In [182]:
max_sal=employee.groupby('DEPARTMENT')['BASE_SALARY'].max()

In [188]:
max_sal.to_frame()

                                BASE_SALARY
DEPARTMENT
Admn. & Regulatory Affairs         140416.0
City Controller's Office            64251.0
City Council                       100000.0
Convention and Entertainment        38397.0
Dept of Neighborhoods (DON)         89221.0
Finance                             96272.0
Fleet Management Department        125884.0
General Services Department         89194.0
Health & Human Services            180416.0
Housing and Community Devp.         98536.0
Houston Airport System (HAS)       186192.0
Houston Emergency Center (HEC)      84456.0
Houston Fire Department (HFD)      210588.0
Houston Information Tech Svcs      102019.0
Houston Police Department-HPD      199596.0
Human Resources Dept.              110547.0
Legal Department                   275000.0
Library                            107763.0
Mayor's Office                     120750.0
Municipal Courts Department        121862.0
Parks & Recreation                  85055.0
Planning & Development              68762.0
Public Works & Engineering-PWE     178331.0
Solid Waste Management             110005.0

In [191]:
type(max_sal)

pandas.core.series.Series

In [192]:
#(employee.merge(max_sal.rename('MAX_SAL_DEP'),how='left',left_on='DEPARTMENT',right_index=True))

(employee.merge(max_sal.rename('MAX_DEPT_SALARY').to_frame(),how='left', left_on='DEPARTMENT',right_index=True))

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE,MAX_DEPT_SALARY
0,0,ASSISTANT DIRECTOR (EX LVL),Municipal Courts Department,121862.0,Hispanic/Latino,Full Time,Female,Active,2006-06-12,2012-10-13,121862.0
1,1,LIBRARY ASSISTANT,Library,26125.0,Hispanic/Latino,Full Time,Female,Active,2000-07-19,2010-09-18,107763.0
2,2,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2015-02-03,2015-02-03,199596.0
3,3,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1982-02-08,1991-05-25,210588.0
4,4,ELECTRICIAN,General Services Department,56347.0,White,Full Time,Male,Active,1989-06-19,1994-10-22,89194.0
5,5,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Black or African American,Full Time,Male,Active,1984-11-26,2005-03-26,199596.0
6,6,ENGINEER,Public Works & Engineering-PWE,71680.0,Asian/Pacific Islander,Full Time,Male,Active,2012-03-26,2012-03-26,178331.0
7,7,CARPENTER,Houston Airport System (HAS),42390.0,White,Full Time,Male,Active,2013-11-04,2013-11-04,186192.0
8,8,DEPUTY ASSISTANT DIRECTOR (EXECUTIVE LEV,Public Works & Engineering-PWE,107962.0,White,Full Time,Male,Active,1993-11-15,2013-01-05,178331.0
9,9,AIRPORT OPERATIONS COORDINATOR,Houston Airport System (HAS),44616.0,NaN,Full Time,Male,Active,2016-03-14,2016-03-14,186192.0
10,10,FIRE FIGHTER,Houston Fire Department (HFD),52644.0,Hispanic/Latino,Full Time,Male,Active,2007-05-21,2008-11-15,210588.0
11,11,"CHIEF PHYSICIAN,MD",Health & Human Services,180416.0,Black or African American,Full Time,Male,Active,1987-05-22,1999-08-28,180416.0
12,12,CUSTOMER SERVICE REPRESENTATIVE I,Public Works & Engineering-PWE,30347.0,Black or African American,Full Time,Male,Active,2015-11-16,2015-11-16,178331.0
13,13,PUBLIC HEALTH INVESTIGATOR SUPERVISOR,Health & Human Services,55269.0,Black or African American,Full Time,Male,Active,1999-10-20,2001-05-19,180416.0
14,14,POLICE SERGEANT,Houston Police Department-HPD,77076.0,Black or African American,Full Time,Male,Active,2001-06-04,2015-05-25,199596.0
15,15,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Black or African American,Full Time,Male,Active,1995-01-30,2015-02-14,199596.0
16,16,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Hispanic/Latino,Full Time,Male,Active,1981-02-23,2002-01-05,199596.0
17,17,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1995-06-19,2007-03-03,199596.0
18,18,MAINTENANCE MECHANIC III,General Services Department,40581.0,Hispanic/Latino,Full Time,Male,Active,2008-12-29,2008-12-29,89194.0
19,19,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,White,Full Time,Male,Active,1992-02-17,2007-07-28,199596.0
20,20,SENIOR INSPECTOR,Public Works & Engineering-PWE,61506.0,White,Full Time,Male,Active,2009-04-06,2015-04-11,178331.0
21,21,FIRE FIGHTER,Houston Fire Department (HFD),57815.0,Black or African American,Full Time,Male,Active,2001-03-20,2003-01-04,210588.0
22,22,INSPECTOR,Public Works & Engineering-PWE,43264.0,Black or African American,Full Time,Male,Active,2015-01-05,2015-01-05,178331.0
23,23,FIRE FIGHTER,Houston Fire Department (HFD),55437.0,White,Full Time,Male,Active,2004-03-15,2005-03-26,210588.0
24,24,POLICE OFFICER,Houston Police Department-HPD,52514.0,Black or African American,Full Time,Male,Active,2010-03-29,2011-03-29,199596.0
25,25,SENIOR POLICE OFFICER,Houston Police Department-HPD,61643.0,White,Full Time,Male,Active,1999-08-23,2012-03-31,199596.0
26,26,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,Hispanic/Latino,Full Time,Male,Active,1979-11-19,2015-12-19,199596.0
27,27,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,White,Full Time,Male,Active,1990-01-12,2004-07-03,199596.0
28,28,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1978-03-13,1994-09-10,199596.0
29,29,UTILITY WORKER,Public Works & Engineering-PWE,29557.0,Black or African American,Full Time,Male,Active,2014-01-21,2014-01-21,178331.0
...,...,...,...,...,...,...,...,...,...,...,...
1970,1970,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Hispanic/Latino,Full Time,Male,Active,1990-06-11,2002-12-07,199596.0
1971,1971,POLICE OFFICER,Houston Police Department-HPD,45279.0,Hispanic/Latino,Full Time,Female,Active,2013-10-14,2014-10-14,199596.0
1972,1972,ENGINEER/OPERATOR,Houston Fire Department (HFD),63166.0,White,Full Time,Male,Active,1990-12-10,2001-04-28,210588.0
1973,1973,SENIOR PROJECT MANAGER,Public Works & Engineering-PWE,77325.0,White,Full Time,Male,Active,2008-08-04,2012-07-07,178331.0
1974,1974,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Black or African American,Full Time,Male,Active,1993-04-12,2013-10-12,199596.0
1975,1975,GROUND TRANSPORTATION REPRESENTATIVE,Houston Airport System (HAS),32157.0,Asian/Pacific Islander,Full Time,Female,Active,1993-05-13,2000-07-15,186192.0
1976,1976,SENIOR SIDELOADER OPERATOR,Solid Waste Management,34466.0,Hispanic/Latino,Full Time,Female,Active,2015-07-20,2016-01-30,110005.0
1977,1977,POLICE OFFICER,Houston Police Department-HPD,45279.0,White,Full Time,Male,Active,2013-06-10,2014-06-10,199596.0
1978,1978,POLICE SERVICE OFFICER,Houston Police Department-HPD,27914.0,Black or African American,Full Time,Female,Active,2011-10-14,2014-03-01,199596.0
1979,1979,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Hispanic/Latino,Full Time,Male,Active,1993-11-08,2006-06-03,199596.0
1980,1980,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,White,Full Time,Male,Active,1983-10-03,2006-05-06,199596.0
1981,1981,CAPTAIN,Houston Fire Department (HFD),70181.0,Black or African American,Full Time,Male,Active,1994-08-29,2013-09-04,210588.0
1982,1982,FIRE FIGHTER,Houston Fire Department (HFD),55437.0,Black or African American,Full Time,Male,Active,2004-01-05,2005-01-14,210588.0
1983,1983,ADMINISTRATIVE SPECIALIST,Admn. & Regulatory Affairs,55172.0,Black or African American,Full Time,Female,Active,2006-10-16,2006-10-16,140416.0
1984,1984,ENGINEER/OPERATOR,Houston Fire Department (HFD),61921.0,White,Full Time,Male,Active,2006-09-11,2014-06-11,210588.0
1985,1985,TRUCK DRIVER,Fleet Management Department,30222.0,Black or African American,Full Time,Male,Active,2013-06-10,2015-08-01,125884.0
1986,1986,POLICE SERGEANT,Houston Police Department-HPD,77076.0,White,Full Time,Male,Active,2001-12-03,2010-12-10,199596.0
1987,1987,SENIOR POLICE OFFICER,Houston Police Department-HPD,NaN,White,Full Time,Male,Active,1977-05-23,2002-01-05,199596.0
1988,1988,SENIOR ASSISTANT CITY ATTORNEY II,Legal Department,124115.0,White,Full Time,Male,Active,2013-01-23,2013-03-02,275000.0
1989,1989,EQUIPMENT WORKER,Public Works & Engineering-PWE,37211.0,Black or African American,Full Time,Male,Active,1984-12-11,2004-09-18,178331.0
1990,1990,BUILDING MAINTENANCE SUPERVISOR,Parks & Recreation,30347.0,Black or African American,Full Time,Female,Active,1995-10-14,2010-03-20,85055.0
1991,1991,MOBILITY SERVICE OFFICER,Houston Police Department-HPD,44429.0,Hispanic/Latino,Full Time,Female,Active,2005-09-12,2007-06-02,199596.0
1992,1992,SECURITY OFFICER,Houston Airport System (HAS),29286.0,Hispanic/Latino,Full Time,Male,Active,2011-12-12,2011-12-12,186192.0
1993,1993,POLICE SERGEANT,Houston Police Department-HPD,81239.0,White,Full Time,Male,Active,1982-05-03,2011-09-03,199596.0
1994,1994,POLICE CAPTAIN,Houston Police Department-HPD,104455.0,Black or African American,Full Time,Male,Active,1983-02-07,2004-07-08,199596.0
1995,1995,POLICE OFFICER,Houston Police Department-HPD,43443.0,White,Full Time,Male,Active,2014-06-09,2015-06-09,199596.0
1996,1996,COMMUNICATIONS CAPTAIN,Houston Fire Department (HFD),66523.0,Black or African American,Full Time,Male,Active,2003-09-02,2013-10-06,210588.0
1997,1997,POLICE OFFICER,Houston Police Department-HPD,43443.0,White,Full Time,Male,Active,2014-10-13,2015-10-13,199596.0
1998,1998,POLICE OFFICER,Houston Police Department-HPD,55461.0,Asian/Pacific Islander,Full Time,Male,Active,2009-01-20,2011-07-02,199596.0
1999,1999,FIRE FIGHTER,Houston Fire Department (HFD),51194.0,Hispanic/Latino,Full Time,Male,Active,2009-01-12,2010-07-12,210588.0

In [197]:
coll_df=pd.read_csv('C://Users//287910031/9781839213106_Code//data/college.csv',index_col='INSTNM')

In [198]:
coll_df.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

In [199]:
coll_df.dtypes

CITY                   object
STABBR                 object
HBCU                  float64
MENONLY               float64
WOMENONLY             float64
RELAFFIL                int64
SATVRMID              float64
SATMTMID              float64
DISTANCEONLY          float64
UGDS                  float64
UGDS_WHITE            float64
UGDS_BLACK            float64
UGDS_HISP             float64
UGDS_ASIAN            float64
UGDS_AIAN             float64
UGDS_NHPI             float64
UGDS_2MOR             float64
UGDS_NRA              float64
UGDS_UNKN             float64
PPTUG_EF              float64
CURROPER                int64
PCTPELL               float64
PCTFLOAN              float64
UG25ABV               float64
MD_EARN_WNE_P10        object
GRAD_DEBT_MDN_SUPP     object
dtype: object

In [201]:
coll_df.MD_EARN_WNE_P10.isna().sum()

1122

In [202]:
coll_df.MD_EARN_WNE_P10.isna().mean()*100

14.890510948905108

In [203]:
coll_df['MD_EARN_WNE_P10'].sample(n=10,random_state=42)

INSTNM
Career Point College                                            20700
Ner Israel Rabbinical College                       PrivacySuppressed
Reflections Academy of Beauty                                     NaN
Capital Area Technical College                                  26400
West Virginia University Institute of Technology                43400
Mid-State Technical College                                     32000
Strayer University-Huntsville Campus                            49200
National Aviation Academy of Tampa Bay                          45000
University of California-Santa Cruz                             43000
Lexington Theological Seminary                                    NaN
Name: MD_EARN_WNE_P10, dtype: object

In [204]:
coll_df['MD_EARN_WNE_P10'].value_counts()

PrivacySuppressed    822
38800                151
21500                 97
49200                 78
27400                 46
37000                 45
29700                 42
28800                 42
25300                 38
22400                 34
33400                 34
29400                 34
29600                 33
28300                 31
25700                 31
36100                 30
23900                 29
47700                 29
30900                 29
29100                 29
27900                 28
25000                 28
24000                 27
21700                 27
28900                 27
27300                 26
21200                 26
28200                 26
31000                 25
22900                 25
                    ...
83800                  1
106900                 1
186500                 1
126500                 1
86700                  1
67700                  1
77800                  1
63300                  1
13900                  1
52500                  1
58500                  1
87200                  1
76900                  1
51300                  1
104800                 1
78700                  1
72400                  1
60900                  1
83100                  1
58800                  1
128800                 1
75200                  1
84200                  1
118800                 1
214400                 1
69000                  1
10400                  1
11300                  1
79200                  1
76200                  1
Name: MD_EARN_WNE_P10, Length: 598, dtype: int64

In [205]:
coll_df.GRAD_DEBT_MDN_SUPP.isna().sum()

32

In [207]:
coll_df.GRAD_DEBT_MDN_SUPP.isna().mean()*100

0.424684804246848

In [208]:
coll_df['GRAD_DEBT_MDN_SUPP'].sample(n=10,random_state=42)

INSTNM
Career Point College                                            14977
Ner Israel Rabbinical College                       PrivacySuppressed
Reflections Academy of Beauty                       PrivacySuppressed
Capital Area Technical College                      PrivacySuppressed
West Virginia University Institute of Technology                23969
Mid-State Technical College                                      8025
Strayer University-Huntsville Campus                          36173.5
National Aviation Academy of Tampa Bay                          22778
University of California-Santa Cruz                             19884
Lexington Theological Seminary                      PrivacySuppressed
Name: GRAD_DEBT_MDN_SUPP, dtype: object

In [209]:
coll_df['GRAD_DEBT_MDN_SUPP'].value_counts()

PrivacySuppressed    1510
9500                  514
27000                 306
25827.5               136
25000                 124
12000                 118
20000                  90
9833                   89
14144                  88
36173.5                81
26000                  64
6333                   60
13000                  58
5500                   52
16500                  43
21500                  41
33000                  39
24750                  36
11000                  35
33523                  33
10500                  33
18331                  33
22141.5                33
7917                   31
7000                   31
9000                   30
19500                  30
19000                  30
20500                  26
40150                  25
                     ...
17772                   1
15106.5                 1
8773                    1
9641.5                  1
26722.5                 1
11677                   1
22105                   1
8498                    1
15378                   1
21612                   1
19351                   1
13964                   1
23266                   1
17492                   1
6734                    1
6789.5                  1
21187.5                 1
30312.5                 1
19980                   1
9427                    1
9774.5                  1
18075                   1
19195.5                 1
32000                   1
22650                   1
13765                   1
21335                   1
37524                   1
25288                   1
11670.5                 1
Name: GRAD_DEBT_MDN_SUPP, Length: 2038, dtype: int64

In [211]:
set(coll_df['MD_EARN_WNE_P10'].apply(type))

{float, str}

In [212]:
set(coll_df['GRAD_DEBT_MDN_SUPP'].apply(type))

{float, str}

In [213]:
set(coll_df['CURROPER'].apply(type))

{int}

In [214]:
cols=['MD_EARN_WNE_P10','GRAD_DEBT_MDN_SUPP']

for col in cols:
    coll_df[col]=pd.to_numeric(coll_df[col],errors='coerce')

In [215]:
set(coll_df['GRAD_DEBT_MDN_SUPP'].apply(type))

{float}

In [220]:
set(coll_df['STABBR'].apply(type))

{str}

In [218]:
coll_df.dtypes

CITY                   object
STABBR                 object
HBCU                  float64
MENONLY               float64
WOMENONLY             float64
RELAFFIL                int64
SATVRMID              float64
SATMTMID              float64
DISTANCEONLY          float64
UGDS                  float64
UGDS_WHITE            float64
UGDS_BLACK            float64
UGDS_HISP             float64
UGDS_ASIAN            float64
UGDS_AIAN             float64
UGDS_NHPI             float64
UGDS_2MOR             float64
UGDS_NRA              float64
UGDS_UNKN             float64
PPTUG_EF              float64
CURROPER                int64
PCTPELL               float64
PCTFLOAN              float64
UG25ABV               float64
MD_EARN_WNE_P10       float64
GRAD_DEBT_MDN_SUPP    float64
dtype: object

In [225]:
college_n=coll_df.select_dtypes(include='number')

In [226]:
college_n.head()

,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,0.0333,0.9353,...,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300.0,33888.0
University of Alabama at Birmingham,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,0.5922,0.2600,...,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700.0,21941.5
Amridge University,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,0.2990,0.4192,...,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100.0,23370.0
University of Alabama in Huntsville,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,0.6988,0.1255,...,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500.0,24097.0
Alabama State University,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,0.0158,0.9208,...,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600.0,33118.5

In [240]:
binary_only= college_n.nunique() ==2

In [250]:
binary_cols=binary_only[binary_only].index.tolist()

In [252]:
college2=college_n.drop(columns=binary_cols)

In [253]:
college2.nunique()

SATVRMID               163
SATMTMID               167
UGDS                  2932
UGDS_WHITE            4397
UGDS_BLACK            3242
UGDS_HISP             2809
UGDS_ASIAN            1254
UGDS_AIAN              601
UGDS_NHPI              363
UGDS_2MOR              957
UGDS_NRA               920
UGDS_UNKN             1517
PPTUG_EF              3420
PCTPELL               4422
PCTFLOAN              4155
UG25ABV               4285
MD_EARN_WNE_P10        597
GRAD_DEBT_MDN_SUPP    2037
dtype: int64

In [256]:
max_cols=college2.idxmax()

In [263]:
max_cols=max_cols.unique()

In [264]:
max_cols[:5]

array(['California Institute of Technology',
       'University of Phoenix-Arizona',
       "Mr Leon's School of Hair Design-Moscow",
       'Velvatex College of Beauty Culture',
       'Thunderbird School of Global Management'], dtype=object)

In [268]:
college2.loc[max_cols].style.highlight_max()

In [270]:
def remove_binary_col(df):
    binary_only= df.nunique()==2
    binary_cols=binary_only[binary_only].index.tolist()
    return df.drop(columns=binary_cols)
    
    
    
def rows_with_max_col (df):
    max_cols=df.idxmax()
    max_cols=max_cols.unique()
    return df.loc[max_cols]

In [278]:
(coll_df
 .assign(MD_EARN_WNE_P10=pd.to_numeric(coll_df.MD_EARN_WNE_P10,errors='coerce'),
        GRAD_DEBT_MDN_SUPP=pd.to_numeric(coll_df.GRAD_DEBT_MDN_SUPP,errors='coerce'))
.select_dtypes(include='number')
.pipe(remove_binary_col)
.pipe(rows_with_max_col)
)

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
California Institute of Technology,765.0,785.0,983.0,0.2787,0.0153,0.1221,0.4385,0.0010,0.0000,0.0570,0.0875,0.0000,0.0000,0.1126,0.2303,0.0082,77800.0,11812.5
University of Phoenix-Arizona,NaN,NaN,151558.0,0.3098,0.1555,0.0760,0.0082,0.0042,0.0050,0.1131,0.0131,0.3152,0.0000,0.6009,0.5920,NaN,NaN,33000.0
Mr Leon's School of Hair Design-Moscow,NaN,NaN,16.0,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.6250,0.6250,0.2000,NaN,15710.0
Velvatex College of Beauty Culture,NaN,NaN,25.0,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2000,0.7692,0.0000,0.5200,NaN,NaN
Thunderbird School of Global Management,NaN,NaN,1.0,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,118900.0,NaN
Cosmopolitan Beauty and Tech School,NaN,NaN,110.0,0.0091,0.0000,0.0182,0.9727,0.0000,0.0000,0.0000,0.0000,0.0000,0.3182,0.7761,0.1244,0.9545,NaN,NaN
Haskell Indian Nations University,430.0,440.0,805.0,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0224,0.8396,0.0000,0.2089,22800.0,NaN
Palau Community College,NaN,NaN,602.0,0.0000,0.0017,0.0000,0.0000,0.0000,0.9983,0.0000,0.0000,0.0000,0.3887,0.8560,0.0000,0.2616,24700.0,NaN
LIU Brentwood,NaN,NaN,15.0,0.0000,0.1333,0.2667,0.0000,0.0000,0.0000,0.5333,0.0000,0.0667,0.4000,0.5652,0.7826,0.7826,44600.0,25499.0
California University of Management and Sciences,NaN,NaN,98.0,0.0102,0.0204,0.0000,0.0408,0.0000,0.0000,0.0000,0.9286,0.0000,0.0000,0.0926,0.0556,0.6852,NaN,NaN
Le Cordon Bleu College of Culinary Arts-San Francisco,NaN,NaN,442.0,0.0317,0.0090,0.0113,0.0271,0.0045,0.0023,0.0113,0.0000,0.9027,0.0000,0.3722,0.5358,0.5440,34000.0,12931.0
MTI Business College Inc,NaN,NaN,146.0,0.2397,0.5137,0.1438,0.0479,0.0342,0.0205,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.3986,23000.0,9500.0
ABC Beauty College Inc,NaN,NaN,38.0,0.2895,0.6579,0.0526,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2105,0.9815,1.0000,0.4688,NaN,16500.0
Dongguk University-Los Angeles,NaN,NaN,20.0,0.3500,0.0000,0.1500,0.5000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,1.0000,NaN,NaN
Medical College of Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233100.0,NaN
Southwest University of Visual Arts-Tucson,NaN,NaN,161.0,0.4534,0.0435,0.3168,0.0062,0.0311,0.0000,0.0000,0.0000,0.1491,0.2795,0.4469,0.4292,0.8657,27200.0,49750.0

In [282]:
college_n=(coll_df
 .assign(MD_EARN_WNE_P10=pd.to_numeric(coll_df.MD_EARN_WNE_P10,errors='coerce'),
        GRAD_DEBT_MDN_SUPP=pd.to_numeric(coll_df.GRAD_DEBT_MDN_SUPP,errors='coerce'))
.select_dtypes(include='number')
.pipe(remove_binary_col)
#.pipe(rows_with_max_col)
)

In [283]:
college_n.max().head()

SATVRMID         765.0
SATMTMID         785.0
UGDS          151558.0
UGDS_WHITE         1.0
UGDS_BLACK         1.0
dtype: float64

In [284]:
college_n.eq(college_n.max()).head()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama at Birmingham,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Amridge University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
University of Alabama in Huntsville,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Alabama State University,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [288]:
has_row_max=college_n.eq(college_n.max()).any(axis='columns')

In [289]:
has_row_max.head()

INSTNM
Alabama A & M University               False
University of Alabama at Birmingham    False
Amridge University                     False
University of Alabama in Huntsville    False
Alabama State University               False
dtype: bool

In [290]:
college_n.eq(college_n.max()).cumsum()

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Piscataway,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Utah County Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
L'esprit Academy - Royal Oak,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Career Institute - Jersey City Branch,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cobb Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Morrow Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Roswell Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Douglasville Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Lithonia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Savannah Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Augusta Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Columbia Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Charleston Campus,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Irving,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Katy,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Northwest Houston,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Plano,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Cedar Hill,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-North Dallas,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-San Antonio,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Strayer University-Stafford,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
WestMed College - Merced,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Vantage College,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
SAE Institute of Technology San Francisco,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Rasmussen College - Overland Park,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
National Personal Training Institute of Cleveland,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Bay Area Medical Academy - San Jose Satellite Location,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2
Excel Learning Center-San Antonio South,1,1,1,109,28,136,1,2,1,1,1,1,44,66,55,12,1,2

In [291]:
(college_n.eq(college_n.max()).cumsum().cumsum())

,SATVRMID,SATMTMID,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,
Alabama A & M University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama at Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Amridge University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
University of Alabama in Huntsville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Alabama State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
The University of Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Central Alabama Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Athens State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University at Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Auburn University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Birmingham Southern College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Chattahoochee Valley Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Concordia College Alabama,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South University-Montgomery,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Enterprise State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
James H Faulkner State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Faulkner University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Gadsden State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
New Beginning College of Cosmetology,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Dothan,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Hanceville,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
George C Wallace State Community College-Selma,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Herzing University-Birmingham,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Huntingdon College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Heritage Christian University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
J F Drake State Community and Technical College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jacksonville State University,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson Davis Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Jefferson State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
John C Calhoun State Community College,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strayer University-Lawrenceville,7280,7280,390,377025,72407,337703,958,11332,3291,5031,1051,7251,112549,171294,168898,35883,3420,10216
Strayer University-Piscataway,7281,7281,391,377134,72435,337839,959,11334,3292,5032,1052,7252,112593,171360,168953,35895,3421,10218
Utah County Campus,7282,7282,392,377243,72463,337975,960,11336,3293,5033,1053,7253,112637,171426,169008,35907,3422,10220
L'esprit Academy - Royal Oak,7283,7283,393,377352,72491,338111,961,11338,3294,5034,1054,7254,112681,171492,169063,35919,3423,10222
National Career Institute - Jersey City Branch,7284,7284,394,377461,72519,338247,962,11340,3295,5035,1055,7255,112725,171558,169118,35931,3424,10224
Strayer University-Cobb Campus,7285,7285,395,377570,72547,338383,963,11342,3296,5036,1056,7256,112769,171624,169173,35943,3425,10226
Strayer University-Morrow Campus,7286,7286,396,377679,72575,338519,964,11344,3297,5037,1057,7257,112813,171690,169228,35955,3426,10228
Strayer University-Roswell Campus,7287,7287,397,377788,72603,338655,965,11346,3298,5038,1058,7258,112857,171756,169283,35967,3427,10230
Strayer University-Douglasville Campus,7288,7288,398,377897,72631,338791,966,11348,3299,5039,1059,7259,112901,171822,169338,35979,3428,10232
Strayer University-Lithonia Campus,7289,7289,399,378006,72659,338927,967,11350,3300,5040,1060,7260,112945,171888,169393,35991,3429,10234
Strayer University-Savannah Campus,7290,7290,400,378115,72687,339063,968,11352,3301,5041,1061,7261,112989,171954,169448,36003,3430,10236
Strayer University-Augusta Campus,7291,7291,401,378224,72715,339199,969,11354,3302,5042,1062,7262,113033,172020,169503,36015,3431,10238
Strayer University-Columbus,7292,7292,402,378333,72743,339335,970,11356,3303,5043,1063,7263,113077,172086,169558,36027,3432,10240
Strayer University-Columbia Campus,7293,7293,403,378442,72771,339471,971,11358,3304,5044,1064,7264,113121,172152,169613,36039,3433,10242
Strayer University-Charleston Campus,7294,7294,404,378551,72799,339607,972,11360,3305,5045,1065,7265,113165,172218,169668,36051,3434,10244
Strayer University-Irving,7295,7295,405,378660,72827,339743,973,11362,3306,5046,1066,7266,113209,172284,169723,36063,3435,10246
Strayer University-Katy,7296,7296,406,378769,72855,339879,974,11364,3307,5047,1067,7267,113253,172350,169778,36075,3436,10248
Strayer University-Northwest Houston,7297,7297,407,378878,72883,340015,975,11366,3308,5048,1068,7268,113297,172416,169833,36087,3437,10250
Strayer University-Plano,7298,7298,408,378987,72911,340151,976,11368,3309,5049,1069,7269,113341,172482,169888,36099,3438,10252
Strayer University-Cedar Hill,7299,7299,409,379096,72939,340287,977,11370,3310,5050,1070,7270,113385,172548,169943,36111,3439,10254
Strayer University-North Dallas,7300,7300,410,379205,72967,340423,978,11372,3311,5051,1071,7271,113429,172614,169998,36123,3440,10256
Strayer University-San Antonio,7301,7301,411,379314,72995,340559,979,11374,3312,5052,1072,7272,113473,172680,170053,36135,3441,10258
Strayer University-Stafford,7302,7302,412,379423,73023,340695,980,11376,3313,5053,1073,7273,113517,172746,170108,36147,3442,10260
WestMed College - Merced,7303,7303,413,379532,73051,340831,981,11378,3314,5054,1074,7274,113561,172812,170163,36159,3443,10262
Vantage College,7304,7304,414,379641,73079,340967,982,11380,3315,5055,1075,7275,113605,172878,170218,36171,3444,10264
SAE Institute of Technology San Francisco,7305,7305,415,379750,73107,341103,983,11382,3316,5056,1076,7276,113649,172944,170273,36183,3445,10266
Rasmussen College - Overland Park,7306,7306,416,379859,73135,341239,984,11384,3317,5057,1077,7277,113693,173010,170328,36195,3446,10268
National Personal Training Institute of Cleveland,7307,7307,417,379968,73163,341375,985,11386,3318,5058,1078,7278,113737,173076,170383,36207,3447,10270
Bay Area Medical Academy - San Jose Satellite Location,7308,7308,418,380077,73191,341511,986,11388,3319,5059,1079,7279,113781,173142,170438,36219,3448,10272
Excel Learning Center-San Antonio South,7309,7309,419,380186,73219,341647,987,11390,3320,5060,1080,7280,113825,173208,170493,36231,3449,10274

In [294]:
has_row_max2=(college_n.eq(college_n.max()).cumsum().cumsum().eq(1).any(axis='columns'))

In [297]:
idmax_cols=has_row_max2[has_row_max2].index

In [298]:
idmax_cols

Index(['Thunderbird School of Global Management',
       'Southwest University of Visual Arts-Tucson', 'ABC Beauty College Inc',
       'Velvatex College of Beauty Culture',
       'California Institute of Technology',
       'Le Cordon Bleu College of Culinary Arts-San Francisco',
       'MTI Business College Inc', 'Dongguk University-Los Angeles',
       'Mr Leon's School of Hair Design-Moscow',
       'Haskell Indian Nations University', 'LIU Brentwood',
       'Medical College of Wisconsin', 'Palau Community College',
       'California University of Management and Sciences',
       'Cosmopolitan Beauty and Tech School', 'University of Phoenix-Arizona'],
      dtype='object', name='INSTNM')

In [304]:
set(college_n.idxmax().unique()) == set(idmax_cols)

True

In [311]:
def idxmax_func(df):
    has_row_max2=(df.eq(college_n.max()).cumsum().cumsum().eq(1).any(axis='columns'))
    return has_row_max2[has_row_max2].index

In [312]:
idxmax_func(college_n)

Index(['Thunderbird School of Global Management',
       'Southwest University of Visual Arts-Tucson', 'ABC Beauty College Inc',
       'Velvatex College of Beauty Culture',
       'California Institute of Technology',
       'Le Cordon Bleu College of Culinary Arts-San Francisco',
       'MTI Business College Inc', 'Dongguk University-Los Angeles',
       'Mr Leon's School of Hair Design-Moscow',
       'Haskell Indian Nations University', 'LIU Brentwood',
       'Medical College of Wisconsin', 'Palau Community College',
       'California University of Management and Sciences',
       'Cosmopolitan Beauty and Tech School', 'University of Phoenix-Arizona'],
      dtype='object', name='INSTNM')

In [315]:
def idxmax_func(df):
    has_row_max2=(df.eq(college_n.max()).cumsum().cumsum().eq(1).any(axis='columns'))
    [lambda df_:df_].index
    return has_row_max

In [316]:
idxmax_func(college_n)

INSTNM
Alabama A & M University                                  False
University of Alabama at Birmingham                       False
Amridge University                                        False
University of Alabama in Huntsville                       False
Alabama State University                                  False
The University of Alabama                                 False
Central Alabama Community College                         False
Athens State University                                   False
Auburn University at Montgomery                           False
Auburn University                                         False
Birmingham Southern College                               False
Chattahoochee Valley Community College                    False
Concordia College Alabama                                 False
South University-Montgomery                               False
Enterprise State Community College                        False
James H Faulkner State Community College                  False
Faulkner University                                       False
Gadsden State Community College                           False
New Beginning College of Cosmetology                      False
George C Wallace State Community College-Dothan           False
George C Wallace State Community College-Hanceville       False
George C Wallace State Community College-Selma            False
Herzing University-Birmingham                             False
Huntingdon College                                        False
Heritage Christian University                             False
J F Drake State Community and Technical College           False
Jacksonville State University                             False
Jefferson Davis Community College                         False
Jefferson State Community College                         False
John C Calhoun State Community College                    False
                                                          ...
Strayer University-Lawrenceville                          False
Strayer University-Piscataway                             False
Utah County Campus                                        False
L'esprit Academy - Royal Oak                              False
National Career Institute - Jersey City Branch            False
Strayer University-Cobb Campus                            False
Strayer University-Morrow Campus                          False
Strayer University-Roswell Campus                         False
Strayer University-Douglasville Campus                    False
Strayer University-Lithonia Campus                        False
Strayer University-Savannah Campus                        False
Strayer University-Augusta Campus                         False
Strayer University-Columbus                               False
Strayer University-Columbia Campus                        False
Strayer University-Charleston Campus                      False
Strayer University-Irving                                 False
Strayer University-Katy                                   False
Strayer University-Northwest Houston                      False
Strayer University-Plano                                  False
Strayer University-Cedar Hill                             False
Strayer University-North Dallas                           False
Strayer University-San Antonio                            False
Strayer University-Stafford                               False
WestMed College - Merced                                  False
Vantage College                                           False
SAE Institute of Technology  San Francisco                False
Rasmussen College - Overland Park                         False
National Personal Training Institute of Cleveland         False
Bay Area Medical Academy - San Jose Satellite Location    False
Excel Learning Center-San Antonio South                   False
Length: 7535, dtype: bool

In [332]:
cols_ugds=col.filter(like='UGDS_')

In [333]:
higher_percentage_race=cols_ugds.idxmax(axis='columns')

In [334]:
higher_percentage_race.head()

INSTNM
Alabama A & M University               UGDS_BLACK
University of Alabama at Birmingham    UGDS_WHITE
Amridge University                     UGDS_BLACK
University of Alabama in Huntsville    UGDS_WHITE
Alabama State University               UGDS_BLACK
dtype: object

In [335]:
higher_percentage_race.value_counts(normalize=True)

UGDS_WHITE    0.670352
UGDS_BLACK    0.151586
UGDS_HISP     0.129473
UGDS_UNKN     0.023422
UGDS_ASIAN    0.012074
UGDS_AIAN     0.006110
UGDS_NRA      0.004073
UGDS_NHPI     0.001746
UGDS_2MOR     0.001164
dtype: float64

In [338]:
cols_ugds[higher_percentage_race=='UGDS_BLACK'].drop(columns='UGDS_BLACK').idxmax(axis='columns').value_counts(normalize=True)

UGDS_WHITE    0.661228
UGDS_HISP     0.230326
UGDS_UNKN     0.071977
UGDS_NRA      0.018234
UGDS_ASIAN    0.009597
UGDS_2MOR     0.006718
UGDS_NHPI     0.000960
UGDS_AIAN     0.000960
dtype: float64